# Generated by Django 5.0.3 on 2024-07-26 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Product",
        ),
    ]
