# Generated by Django 5.0.3 on 2024-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_productcategory_order_orderitem_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
