# Generated by Django 5.0.3 on 2024-07-27 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestItem",
        ),
    ]
